baseurl: https://mkosakana.github.io/
publishDir: docs
canonifyurls: true
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: developer mkosakana 🐟

languages:
    en:
        languageName: English
        title: Masaki Arai / mkosakana
        weight: 1
    ja:
        languageName: Japanese
        title: 新井柾生 / mkosakana
        weight: 1

# Change it to your Disqus shortname before using
disqusShortname: mkosakana

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: ar, ca, de, el, en, es, fr, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: ja

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /images/favicon.ico

    footer:
        since: 2021
        customText:

    dateFormat:
        published: Jan 02, 2022
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🍥
        subtitle: A Web developer in Japan. ― work as a backend engineer with Go, TypeScript, and more. 춤추듯 살자.
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: true
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: giscus

        disqusjs:
            shortname: mkosakana
            apiUrl:
            apiKey: q4ZKvDQrbS8F1McDXlei0SheXb89JGZJ2G9hHudDK2RPk3rsWsEVSJAqWRO68zw1
            admin: Masaki Arai
            adminLabel:

        utterances:
            repo: mkosakana/mkosakana.github.io
            issueTerm: url
            label: comment

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

        twikoo:
            envId:
            region:
            path:
            lang:

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

        giscus:
            repo: mkosakana/mkosakana.github.io
            repoID: R_kgDOHIewAQ
            category: General
            categoryID: DIC_kwDOHIewAc4COdLN
            mapping: url
            darkTheme: dark_dimmed
            reactionsEnabled: 100
            emitMetadata: 100

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site: mkosakana

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: true
            local: true
            src: img/avatar.png

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - params:
              newTab: false

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/mkosakana
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com/mkosakana
          params:
              icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
